#!/bin/bash

echo "Installing xcode command line tools..."
xcode-select --install

if ! command -v brew > /dev/null 2>&1; then
    echo "Installing homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew already installed!"
fi

if [ -f "$HOME/.Brewfile" ]; then
    echo "Installing homebrew packages using Brewfile"
    brew bundle --global
fi

echo "Installing terminal fonts..."
mkdir /tmp/terminus-font && cp $HOME/.config/yadm/resources/terminus-font.zip /tmp/terminus-font/terminus-font.zip
cd /tmp/terminus-font && unzip Terminus.zip && mv *.ttf ~/Library/Fonts/

echo "Installing neovim..."
git clone https://github.com/neovim/neovim /tmp/neovim && cd /tmp/neovim
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
mkdir ~/.config/nvim/
mkdir ~/.local/share/nvim

echo "Installing tmux plugin manager"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "Refreshing tmux environment"
tmux source ~/.tmux.conf

echo "Installing tmux plugins"
sh .tmux/plugins/tpm/bin/install_plugins

echo "Installing oh-my-zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "Installing zsh theme"
curl -0 https://raw.githubusercontent.com/devsdmf/zsh-theme/master/devsdmf.zsh-theme > $HOME/.oh-my-zsh/themes/devsdmf.zsh-theme

echo "Reverting .zshrc file"
mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc

echo "Installation finished, restart the terminal emulator!"
