#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin"  ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile"  ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  install_oh_my_zsh
  install_zsh_theme
  revert_zsh_file
  reload_zsh

elif [ "$system_type" = "Linux" ]; then
  # install packages
  echo "Installing shell essentials..."
  sudo apt-get install -y zsh tmux coreutils openssl wget curl tree cmake dirmngr apt-transport-https ca-certificates gnupg2 software-properties-common # default tools

  echo "Installing essential tools..."
  sudo apt-get install -y htop ncdu silversearcher-ag

  download_and_install_binary https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping prettyping # prettyping
download_and_install_binary https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy diff-so-fancy # diff-so-fancy

  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

  echo "Installing development tools..."
  sudo apt-get install -y gcc llvm python python3

  # docker
  curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  
  # add php installation here

  # java 8
  echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/webupd8team-java.list
  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/webupd8team-java.list
  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
  sudo apt-get update && sudo apt-get install -y oracle-java8-installer && sudo apt-get install oracle-java8-set-default

  # ant maven
  sudo apt-get install ant maven

  # scala
  echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  sudo apt-get update && sudo apt-get install -y sbt scala

  echo "Setting up zsh as default shell..."
  chsh -s $(which zsh)

  install_oh_my_zsh
  install_zsh_theme
  revert_zsh_file
  reload_zsh
fi

function install_oh_my_zsh {
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

function install_zsh_theme {
  echo "Installing zsh theme..."
  curl -0 https://raw.githubusercontent.com/devsdmf/zsh-theme/master/devsdmf.zsh-theme > $HOME/.oh-my-zsh/themes/devsdmf.zsh-theme
}

function revert_zsh_file {
  echo "Reverting .zshrc file..."
  mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
}

function reload_zsh {
  echo "Reloading shell..."
  exec zsh
}

function download_and_install_binary {
    echo "Downloading $2 ..."
    curl -0 $1 > /tmp/$2
    sudo mv /tmp/$2 /usr/local/bin/$2 && sudo chmod +x /usr/local/bin/$2
}
